@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
    participant "Authentication Server"
    participant "Logic Server"
    participant "SMTP Yandex"
    database "Credential Database"
    database "Housing Database"

    User -> "Authentication Server" :<b> POST /send-ver-code?email=... \nВ теле запроса пароль и подтверждение пароля
    "Authentication Server" -> "Authentication Server" : Генерация кода верификации
    "Authentication Server" -> "Credential Database" : Добавление записи о пользователе в\nбазу данных учетных записей
    "Credential Database" --> "Authentication Server" : Возврат статуса операции
    "Authentication Server" -> "SMTP Yandex" : Запрос на почтовый сервер для отправки письма с кодом верификации
    "SMTP Yandex" --> User : Отправка кода пользователю
    User -> "Authentication Server" : <b>POST /add-user \nВ теле запроса данные учетной записи
    "Authentication Server" -> "Authentication Server" : Проверка кода верификации
    "Authentication Server" -> "Credential Database" :Обновление статуса учетной записи (Active)
    "Authentication Server" -> "Logic Server" :<b>POST /activate-user/email \nЗапрос к основному серверу для активации пользователя
    "Logic Server" -> "Housing Database" : Активация пользователя в базе данных
    "Housing Database" --> "Logic Server" :Статус операции
    "Logic Server" --> "Authentication Server" :Статус операции
    "Logic Server" --> User :<b>200 OK
@enduml